name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH
      run: sudo apt-get update && sudo apt-get install -y openssh-client
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: anpiz/realcheck
      
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
   
    - name: Connect and exit
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pwd && ls -la && sudo docker rm -f realcheck && sudo docker image prune -af && sudo docker run -d --name realcheck --pull always -p 3000:3000 -p 5000:5000 anpiz/realcheck && exit"
