name: Build and Deploy Python app to Azure Web App 🚀

env:
  AZURE_WEBAPP_NAME: apirealcheck   # set this to your application's name
  PYTHON_VERSION: '3.10'           # set this to the Python version to use

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Set up dependency caching for faster installs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add a step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: <publishData><publishProfile profileName="apirealcheck - Web Deploy" publishMethod="MSDeploy" publishUrl="apirealcheck.scm.azurewebsites.net:443" msdeploySite="apirealcheck" userName="$apirealcheck" userPWD="mYGFs3JJmijge9dcx0YnZiphy4hXHGNCTX7xALQHrMxSkT91rpBa32cixAN4" destinationAppUrl="https://apirealcheck.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="apirealcheck - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-431.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="apirealcheck\$apirealcheck" userPWD="mYGFs3JJmijge9dcx0YnZiphy4hXHGNCTX7xALQHrMxSkT91rpBa32cixAN4" destinationAppUrl="https://apirealcheck.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="apirealcheck - Zip Deploy" publishMethod="ZipDeploy" publishUrl="apirealcheck.scm.azurewebsites.net:443" userName="$apirealcheck" userPWD="mYGFs3JJmijge9dcx0YnZiphy4hXHGNCTX7xALQHrMxSkT91rpBa32cixAN4" destinationAppUrl="https://apirealcheck.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
